CREATE DATABASE DC_COMICS
USE DC_COMICS

CREATE TABLE HEROES(
  ID VARCHAR(50) NOT NULL,
  SUPERHERO VARCHAR(25) NOT NULL,
  PUBLISHER VARCHAR(25) NOT NULL,
  ALTEREGO VARCHAR(25) NOT NULL,
  FIRSTAPPEARANCE VARCHAR(50) NOT NULL,
  CHARACTERS VARCHAR(200) NOT NULL,
  IMAGEURL VARCHAR(250) NOT NULL,
  ISACTIVE BIT NOT NULL DEFAULT 0

)
--==========================
CREATE TABLE USERS (
ID INT IDENTITY(1,1) NOT NULL,
USERNAME VARCHAR(25) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(25) NOT NULL,
ISACTIVE BIT NOT NULL DEFAULT 0,
ISLOGGED BIT NOT NULL DEFAULT 0
)